### ISSUE TITLE
Issue Indicated by ATM8 Dev.

### ISSUE THREAD

**Issue by Dreamspectre** [ChaoticTrials/UtilitiX#34]
AllTheMods8 Dev Mitchell52 indicated that a crash when travelling through The End portal may be caused due to an issue with UtilitiX in ATM v1.0.13. Players walk through The End portal, spawn in new dimension with no items at all and no terrain or structures load - just background art (looks like an Aurora Borealis). Players continue to fall (as evidenced by a decreasing Y value in the coordinates under the map) until the server crashes. Crash-log below.

https://mclo.gs/KOSNbrh

**Comment by MelanX** [comment]
I tried to reproduce it. I created a new world, grabbed a few items, teleported to end portal. Then I startet profiling with `/spark profiler start`, jumped into the portal, waited for me to land on the obsidian island, and then used `/spark profiler stop`. Here's the result: https://spark.lucko.me/Wme6rMmY36
Looking at what UtilitiX does in this time, it's nearly impossible that it's causing the crash. 
![image](https://user-images.githubusercontent.com/26039509/223207733-648d3d4b-3cca-4ea6-96bc-f4887f4ce7c1.png)

Yes, I know - the log says that UtilitiX is involved. But you can't see why it's crashing, what's causing the long load time. Yes, your log was taken from a server, which is why it took 3 minutes and then the crash (tick took too long) and I can't reproduce this in singleplayer. I just want to tell you: maybe it's something else. I can't believe that UtilitiX is the problem for that. Especially the things listed in the linked report. It's just this: `level.getBlockState(thePos)`. It's called so often each tick by so many other methods. 

I hope you'll find the true cause, or an evidence that UtilitiX is causing the problem. It's a big pack, sadly every little performance decrease together could have such an impact that it just have to crash.
