### ISSUE TITLE
Duplicating Levels

### ISSUE THREAD

**Issue by EliteScouter** [ChaoticTrials/UtilitiX#46]
### Minecraft version

1.20.1

### LibX version

1.20.1-5.0.5

### UtilitiX version

1.20.1-0.8.2

### Forge version

47.1.3

### The latest.log file

N/A

### Issue description

The mod is used on ATM9, I noticed when I store "1 Level" it actually stores 67 into the crystal but only takes 1 level from my experience. I can then use the 67 levels to export to a container. This is allowing you to only store 1 level but get 67 out of the crystal if exported.

### Steps to reproduce

1. Create a crystal
2. Store 1 level (it will show 67)
3. Use pipe to export the 67 levels into a container.
4. You now have exported 67 levels but only gave it 1 level.

**Comment by MelanX** [comment]
How many levels do you have? If you have 100 levels and store 1 level, it'll drain 1 level from you, so you'll have 99 levels left. From level 99 to level 100, it's 733 xp points. 733 xp points is equal to nearly 23 levels. That means, the crystal will show 22 levels (and a half full xp bar). 
If you store all your 100 levels and retrieve 1 level, it'll only retrieve the 7 xp points needed to set you to level 1. This means, the levels in the crystal are 99, and xp bar is nearly full. 

If you know that and I misunderstood your issue, please tell me. Otherwise, this can be closed :)
